### ISSUE TITLE
Display issue for Proposal attachments in edit view

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3317] opened 2017-08-28 09:07 UTC
Way too much whitespace between checkbox and label.

![screen shot 2017-08-28 at 11 04 49](https://user-images.githubusercontent.com/736583/29766979-feb58552-8be0-11e7-9605-13e77f2cd1c1.png)

**Comment by Rotonen** [comment] 2017-08-29 14:28
Fixed in 4teamwork/plonetheme.teamraum/#577.

Not very fond of fixing in CSS what is caused by non-uniform HTML generation.

The create form 'add documents' widget generates different HTML (the input element is nested in the label element) after document generation than the edit form displays (the input element is a peer of the label element).

**Closed** 2017-09-04 10:36 UTC
Labels: SPV, UI
