### ISSUE TITLE
ftw.flamegraph zu GEVER dependencies hinzufügen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5744] opened 2019-06-21 13:26 UTC
Bei Performance Problemen in der Produktion ist es hilfreich wenn man gleich die Funktionalitäten von ftw.flamegraph verwenden kann.

**Comment by njohner** [comment] 2019-08-26 12:28
As discussed in https://github.com/4teamwork/opengever.core/pull/5882, the problem is that if `ftw.flamegraph` is installed, it is available for all users, so that any user can see the full trace for any request he can make. We can't make it manager only, as we want the flamegraph to work for cases where `zauth` is used to impersonate another user, and it is not possible to distinguish an impersonated user from another user.
We therefore let it be for now and just close this issue.

**Closed by njohner** 2019-08-26 12:28 UTC
