### ISSUE TITLE
Meeting zip export of a meeting fails if there is no agenda item list template set on the committee container

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3338] opened 2017-08-31 20:09 UTC
This could be handled gracefully in the zip exporter.

It is likely this issue has many near cousins as well so some exploratory work to find and fix those as well is welcome.

**Comment by jone** [comment] 2017-10-23 15:41
@tarnap could you take a look at this one?
I think there is an `if`-statement missing in the zip export:
when there is no agenda item list, and there is no template for generating it, we shouldn't try.

**Comment by tarnap** [comment] 2017-10-25 09:49
When does that happen? @jone said:
1. Meeting has agenda items
2. Agenda item list has not been generated yet
3. There is no template for the agenda item list
4. Zip file is generated

**Comment by Rotonen** [comment] 2017-10-25 12:42
I unfortunately did not record the path to get to that state as this was stumbled upon when touching something else, but the zip exporter(s) should still handle the case.

**Comment by tarnap** [comment] 2017-10-25 13:19
I was able to reproduce the error.
When the `word meeting` flag is enabled, the issue is solved by using the `MergeDocxProtocolCommand` instead of the `CreateGeneratedDocumentCommand`.
I'll reproduce the error without the `word meeting` flag enabled.

**Comment by jone** [comment] 2017-10-25 13:48
```python
2017-10-25 15:47:54 ERROR Zope.SiteErrorLog 1508939274.80.101005544016 http://localhost:8080/fd/sitzungen/committee-5/meeting-88/export-meeting-zip
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module opengever.meeting.browser.meetings.zipexport, line 26, in __call__
  Module opengever.meeting.browser.meetings.zipexport, line 51, in generate_zip
  Module opengever.meeting.browser.meetings.zipexport, line 144, in get_agendaitem_list
  Module opengever.meeting.command, line 250, in generate_file_data
  Module opengever.meeting.command, line 91, in get_sablon_template
AgendaItemListMissingTemplate
```

**Closed** 2017-10-27 14:44 UTC
Labels: Bug, SPV
