### ISSUE TITLE
BadZipfile Error during Docproperty Update

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2145] opened 2016-09-07 12:41 UTC
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/1241/

```
BadZipfile: Bad CRC-32 for file 'word/media/image1.jpeg'
(34 additional frame(s) were not displayed)
...
  File "python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "python2.7/zipfile.py", line 632, in read
    data = self.read1(n - len(buf))
  File "python2.7/zipfile.py", line 672, in read1
    self._update_crc(data, eof=(self._compress_left==0))
  File "python2.7/zipfile.py", line 647, in _update_crc
    raise BadZipfile("Bad CRC-32 for file %r" % self.name)
```

More informations including the file --> [Extranet Ticket](https://extranet.4teamwork.ch/support/edk/tracker-support-gever-edk/34)

**Comment by lukasgraf** [comment] 2016-12-19 15:45
Caused by a corrupted Word-Document, closing.

**Closed by lukasgraf** 2016-12-19 15:45 UTC
Labels: bug
