### ISSUE TITLE
UnicodeEncodeError: When moving items in the contenttree widget autocomplete field.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#610] opened 2014-10-09 09:34 UTC
```
/home/zope/eggs/Zope2-2.13.18-py2.7.egg/ZPublisher/Publish.py:126→ publish
/home/zope/eggs/Zope2-2.13.18-py2.7.egg/ZPublisher/mapply.py:77→ mapply
/home/zope/eggs/Zope2-2.13.18-py2.7.egg/ZPublisher/Publish.py:46→ call_object
/home/zope/eggs/plone.formwidget.autocomplete-1.2.1_opengever_1.2-py2.7.egg/plone/formwidget/autocomplete/widget.py:69→ __call__
```

See [Errbit Error](https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/5301e38e3838182e0c000d6f) for more details and description how to produce.

**Comment by deiferni** [comment] 2015-01-22 12:58
Probably data was fixed in the meantine. Cannot reproduce this problem any more. If it should occur again it has to be fixed in our fork of `plone.formwidget.autocomplete`.

**Closed by deiferni** 2015-01-22 12:58 UTC
Labels: 0 - Backlog, bug
