### ISSUE TITLE
Template filter does not work with umlauts.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4320] opened 2018-05-17 16:42 UTC
When i filter

![screen shot 2018-05-17 at 18 35 40](https://user-images.githubusercontent.com/736583/40191273-3ed95cc8-5a01-11e8-9eef-1d4cf64a1632.png)

with

![screen shot 2018-05-17 at 18 40 53](https://user-images.githubusercontent.com/736583/40191441-dc9f460c-5a01-11e8-8d4a-2449eb150212.png)

the documents that should be visible are not.

Other non-ascii characters will most likely also be a problem.

Also we use that filter in other places, not only for templates, so please double check!

**Comment by Rotonen** [comment] 2018-05-17 16:51
Cannot reproduce locally, but not dismissing the issue. Very curious - probably should normalise somewhere.

https://github.com/4teamwork/opengever.core/blob/9be72fe67e58834d36530f075e50024dba736d3f/opengever/base/browser/resources/TableRadioWidget.js#L13

This check seems to be fragile, but don't know what to.

@bierik ideas?

**Comment by bierik** [comment] 2018-05-18 07:49
`td.textContent.trim().toUpperCase().indexOf(text)` is the text in uppercase too here? `text` should be in uppercase as well, right?
Because `'halööööö'.toUpperCase().trim().indexOf('Ö')` is working fine and gives me `3`.

**Comment by Rotonen** [comment] 2018-05-22 10:29
I think this is something along the lines of `U+00FC` vs. `U+1E73` for representing `ü`.

**Comment by Rotonen** [comment] 2018-05-22 11:48
I'll need to pull in a polyfill for this to work proper also on ECMAScript 5 / IE 11:
https://github.com/walling/unorm

This has gotten out of hand for me in regards to the associated tooling complexity, assigning to @bierik.

Recommended reference reading:
https://mathiasbynens.be/notes/javascript-unicode
https://dmitripavlutin.com/what-every-javascript-developer-should-know-about-unicode/

**Closed** 2018-05-24 16:34 UTC
Labels: Bug
